# General Jekyll Config
highlighter: rouge
url: https://pinedance.github.io
lsi: false
exclude: ["LICENSE", "README.md", ".ruby-version", ".gitignore", "Gemfile", "Gemfile.lock", "_buildPostFromMP3.rb"]

# Site Settings
baseurl:            "/podcast02" # Base URL must end WITHOUT a slash, default: ""
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
host: localhost
port: 8384
